### ISSUE TITLE
Add xrpl as a project that uses lerna

### ISSUE THREAD

**Issue by ledhed2222** [lerna/website#112]
Didn't know where else to put this. 

https://github.com/XRPLF/xrpl.js is using lerna now

this is the official js/ts library for the XRPL crypto ledger (sometimes incorrectly called Ripple)

Please add us to your site!

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

We have just pushed out a new version of the website, which we will continue to iterate on, we hope you like it and find it useful!

We've initially gone for a very small subset of users on this redesign, but I'll leave this issue open in case we want to figure out a way to be more comprehensive around that.

Many thanks 🙏

**Comment by JamesHenry** [comment]
Any changes and issues should please be submitted over on https://github.com/lerna/lerna

This repo exists purely to maintain the github pages integration for the domain we inherited
