### ISSUE TITLE
Add Warning for Unmaintained Project

### ISSUE THREAD

**Issue by dawsonc623** [lerna/website#114]
Just saw on the Lerna repo that this project is now considered unmaintained. The website should probably be updated for clarity, as well.

**Comment by JamesHenry** [comment]
Hi Folks 👋 

You may or may not know that lerna is now under the stewardship of Nrwl (announcement here https://github.com/lerna/lerna/issues/3121), a company with a long history of not just producing valuable open-source software (OSS), but also backing others (at the time of writing, Nrwl has donated over $50,000 to OSS it _hasn't_ created, see https://opencollective.com/nx for full details).

Quite simply, Nrwl ❤️  OSS, and is committed to making lerna the best it can be. We use it ourselves.

We hope you will continue to be a part of this community as we look to take things forward from here!

Please see https://github.com/lerna/lerna/discussions/3140 for more details on our plans for 2022.

We have just pushed out a new version of the website, which we will continue to iterate on, we hope you like it and find it useful!

Feel free to open a new issue on here if you spot anything that needs fixing or improving.

Many thanks 🙏
