### ISSUE TITLE
Cannot find getting-started-example

### ISSUE THREAD

**Issue by tobysmith568** [lerna/website#116]
The page https://lerna.js.org/docs/core-concepts/versioning-and-publishing links to https://github.com/lerna/getting-started-example
but that repository has either been deleted, moved, or made private.

**Comment by tobysmith568** [comment]
This page also links to it: https://lerna.js.org/docs/core-concepts/bootstrapping

**Comment by tobysmith568** [comment]
And this page: https://lerna.js.org/docs/core-concepts/running-tasks

**Comment by juristr** [comment]
@tobysmith568 sorry for that. Looks like the repo was still private. Should be fixed now 😃

**Comment by tobysmith568** [comment]
Great, thanks :)
