### ISSUE TITLE
Slackin instance down

### ISSUE THREAD

**Issue by elainemckinley** [lerna/website#47]
From here: https://github.com/lerna/lerna/issues/1404

https://slack.lernajs.io directs to a Heroku 'No such app' page. The link there is in the project's README.

**Comment by steveoh** [comment]
can I get an invite please

**Comment by JamesHenry** [comment]
Hi folks, if you want to join a lerna related slack, please head over the to the Nrwl Community one and join the #lerna channel

https://nrwlcommunity.slack.com/

Many thanks 🙏
